package me.zhaotb.db.api.model;

public class AppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_id
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.comands
     *
     * @mbggenerated
     */
    private String comands;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_id
     *
     * @return the value of app_info.app_id
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_id
     *
     * @param appId the value for app_info.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_name
     *
     * @return the value of app_info.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_name
     *
     * @param appName the value for app_info.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.class_name
     *
     * @return the value of app_info.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.class_name
     *
     * @param className the value for app_info.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.comands
     *
     * @return the value of app_info.comands
     *
     * @mbggenerated
     */
    public String getComands() {
        return comands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.comands
     *
     * @param comands the value for app_info.comands
     *
     * @mbggenerated
     */
    public void setComands(String comands) {
        this.comands = comands == null ? null : comands.trim();
    }
}