package me.zhaotb.db.api.dao;

import java.util.List;
import me.zhaotb.db.api.model.AppInfo;
import me.zhaotb.db.api.model.AppInfoExample;
import org.apache.ibatis.annotations.Param;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insertSelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    List<AppInfo> selectByExample(AppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    AppInfo selectByPrimaryKey(Long appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppInfo record, @Param("example") AppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppInfo record, @Param("example") AppInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppInfo record);
}