server:
  port: 9200

spring:
  application:
    name: eureka-center
  profiles:
    active: study
  security:
    user:
      name: test  # 用户名
      password: 123456   # 密码

eureka:
  environment: "study"
  instance:
    hostname: 132.126.3.28
    prefer-ip-address: true
    dataCenterInfo:
      com.netflix.appinfo.MyDataCenterInfo: MyOwn #没起作用，应该是要去做一下类转换处理. -- 这里的数据中心目前默认aws
  client:
    region: wuHan
    availability-zones:
      wuHan: "hongShan"
      chongQing: "yuBei,heChuan"
    registerWithEureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: "http://test:123456@132.126.3.28:${server.port}/eureka/"
      hongShan: "http://test:123456@132.126.3.28:9201/eureka/"
      yuBei: "http://test:123456@132.126.3.28:9202/eureka/"
      heChuan: "http://test:123456@132.126.3.28:9203/eureka/"
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

