server:
  port: 9100

spring:
  application:
    name: config-client
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 172.16.52.69:9092

eureka:
  client:
    region: wuHan
    availability-zones:
      wuHan: "hongShan"
      chongQing: "yuBei,heChuan"
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      hongShan: "http://test:123456@132.126.3.28:9201/eureka/"
      yuBei: "http://test:123456@132.126.3.28:9202/eureka/"
      heChuan: "http://test:123456@132.126.3.28:9203/eureka/"

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

