server:
  port: 18080

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true
  endpoints:
    web:
      base-path: "/management/"


spring:
  application:
    name: me

