server:
  port: 18080
spring:
  thymeleaf:
    enabled: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: abcdefghijkmpl
  patterns:
    - "/test/*"
    - "/file/*"

savePath: /F:/tmp/saveFiles/
